server:
  port: 7070

spring:
  kafka:
    bootstrap-servers: kafka:9092,kafka1:9093,kafka2:9094
    consumer:
      auto-offset-reset: earliest
    streams:
      client-id: interactive-query-streams
      application-id: interactive-query
      replication-factor: 3
    properties:
      cache.max.bytes.buffering: 10485760
      application.server: localhost:7070

logging:
  level:
    root: info

application:
  name: interactive-query
  kafka:
    topics:
      flight-topic-name: flights
    stores:
      flight-store-name: flight-count
  web:
    country-count-uri: "/countFrom/{country}"