server:
  port: 7890
application:
  name data-provider

spring:
  kafka:
    topics:
      flights-topic-name: flights
    bootstrap-servers: kafka:9092,kafka1:9093,kafka2:9094
    producer:
      acks: all
      retries: 3
      client-id: data-provider
    properties:
      retry.backoff.ms: 10000
      reconnect.backoff.max.ms: 10000
      request.timeout.ms: 5000
  webClient:
    base-url: https://opensky-network.org/api
    all-uri: /states/all
    connection:
      connectionTimeout: 20000
      readTimeout: 20000
